Cver cli (#82)

diff --git a/.github/workflows/regression-ingest.yaml b/.github/workflows/regression-ingest.yaml
--- a/.github/workflows/regression-ingest.yaml
+++ b/.github/workflows/regression-ingest.yaml
@@ -17,7 +17,7 @@ on:
         type: string
 
 jobs:
-  regression-engine:
+  regression-ingest:
     runs-on: self-hosted
     container:
       image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
@@ -29,7 +29,6 @@ jobs:
       # This needs to be updated before staging can use it.
       - name: Execute Tests
         run: |
-          # @todo: Make this more dynamic
           if [ "${{ inputs.deployment-name }}" = "test" ]; then
             NAMESPACE="cver-test"
           else  
@@ -38,8 +37,28 @@ jobs:
           mkdir ~/.kube
           echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
           export KUBECONFIG=~/.kube/config.yaml
-          kubectl create job --from=cronjob/cver-ingest-test-${{ inputs.run-number }}" cver-ingest-test-${{ inputs.run-number }}-manual
-          TEST_POD=$(kubectl get -n ${NAMESPACE} pods -l app.kubernetes.io/instance=cver-engine-${{ inputs.deployment-name }}-${{ inputs.run-number }} --no-headers | cut -d' ' -f1)
-          kubectl exec -n ${NAMESPACE} -it ${TEST_POD} -- echo "helo world"
+
+          CRON_JOB="cver-ingest-test-${{ inputs.run-number }}"
+          echo "Creating job: ${CRON_JOB}"
+          kubectl create job -n ${NAMESPACE} --from=cronjob/${CRON_JOB} ${CRON_JOB}
+          elapsed_time=0
+          # Loop until the elapsed time reaches 300 seconds
+          while [ $elapsed_time -lt 300 ]; do
+              echo "Executing the command..."
+              TEST_POD=$(kubectl get -n ${NAMESPACE} pods -l job-name=${CRON_JOB} --no-headers | awk '{print $3}')
+              echo $TEST_POD
+              if [ "${TEST_POD}" = "Completed" ]; then
+                  echo "Job executed successfully: ${TEST_POD}"
+                  exit 0
+              elif [ $TEST_POD = "Error" ]; then
+                  echo "Job failed"
+                  exit 1
+              fi
+              sleep 10
+              # Increment the elapsed time by 10 seconds
+              elapsed_time=$((elapsed_time + 10))
+          done
+          echo "Giving up after 300 seconds."
+          exit 1
 
 # End File: cver/.github/workflows/regression-ingest.yaml
